pipeline {

    agent any
    
    stages {
        
        stage('Build') {

            def dirpath = "SpringbootRestAPI"
            dir(dirpath){
            //logic
            
            sh '''
            export GRADLE_USER_HOME=~/.gradle
            ./gradle clean build --info
            '''
            }
        }
        
    }
}