pipeline {

    agent any
  
    stages {
        stage('Dependencies') {
            steps {
                dir("ReactApp"){
                sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir("ReactApp"){
                sh 'npm run-script build'
                }
            }
        }
        stage('Delivery') {
            steps {
                //sh 'cp --recursive build /'
                echo 'delivered'
            }
        }

    }
}