pipeline {

    agent any
    
    stages {
        
        stage('Build') {
            sh '''
            export GRADLE_USER_HOME=~/.gradle
            ./gradlew clean build --info
            '''
        }
        
    }
}